function conditionDir = paramsToDirName(gaborParams,temporalParams,oiParams,mosaicParams,rgcParams)

theGaborName = sprintf('cpd%d_sfov%d_fwhm%d',...
    gaborParams.cyclesPerDegree,...
    gaborParams.gaussianFWHMDegs,...
   gaborParams.gaussianFWHMDegs);

theTemporalName = sprintf('tau%d_dur%d_em%d',...
    temporalParams.windowTauInSeconds, ...
    temporalParams.stimulusDurationInSeconds, ...
    temporalParams.eyeMovements);

theOIName = sprintf('blur%d_lens%d', ...
    oiParams.blur, ...
    oiParams.lens);

theMosaicName = sprintf('LMS%d%d%d_mfov%d',...
    mosaicParams.LMSRatio(1),mosaicParams.LMSRatio(2),mosaicParams.LMSRatio(3), ...
    mosaicParams.fieldOfViewDegs);

conditionDir = [theGaborName '_' theTemporalName '_' theOIName '_' theMosaicName];
